name: Publishing NPM package

on:
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Build storybook
        run: yarn build:storybook

      - name: Deploy storybook
        run: yarn storybook-to-ghpages --existing-output-dir=storybook-dist --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GH_TOKEN }}

      - name: Build app
        run: yarn build

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag-prefix: 'v'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.ACTION_PUBLISH_TOKEN }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Notify slack of successful deploy
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C0255H2GNK0\",\"text\":\"Successfully published PUI ${{ steps.package-version.outputs.current-version }} ! :rocket:\"}'
        if: success()
