// import './styles.scss';

// import { storiesOf } from '@storybook/react';

// import AccordionStory from './accordion';
// import AvatarStory from './avatar';
// import AvatarGroupStory from './avatar-group';
// import ButtonsStory from './buttons';
// import CheckboxStory from './checkbox';
// import ChipStory from './chip';
// import DayPickerStory from './day-picker';
// import DropzoneStory from './dropzone';
// import FormsStory from './forms';
// import GridStory from './grid';
// import IconsStory from './icons';
// import PaginationStory from './pagination';
// import PopupStory from './popup';
// import RadioStory from './radiobutton';
// import ResponsiveTableStory from './responsive-table';
// import SelectStory from './select';
// import SliderStory from './slider';
// import StampStory from './stamp';
// import SwitchStory from './switch';
// import TabStory from './tabs';
// import TextStory from './text';

// storiesOf('Accordion', AccordionStory);
// storiesOf('Avatar', AvatarStory);
// storiesOf('AvatarGroup', AvatarGroupStory);
// storiesOf('Button', ButtonsStory);
// storiesOf('Chip', ChipStory);
// storiesOf('CheckBox', CheckboxStory);
// storiesOf('DayPicker', DayPickerStory);
// storiesOf('Dropzone', DropzoneStory);
// storiesOf('Grid', GridStory);
// storiesOf('Icon', IconsStory);
// storiesOf('Icon', TextStory);
// storiesOf('Forms', FormsStory);
// storiesOf('Pagination', PaginationStory);
// storiesOf('Popup', PopupStory);
// storiesOf('RadioButton', RadioStory);
// storiesOf('ResponsiveTable', ResponsiveTableStory);
// storiesOf('Select', SelectStory);
// storiesOf('Slider', SliderStory);
// storiesOf('Stamp', StampStory);
// storiesOf('Switcher', SwitchStory);
// storiesOf('Tab', TabStory);
